version: '3.8'

services:
  db-test:
    image: postgres:14.2-alpine
    ports:
      - 5437:5432
    environment:
      POSTGRES_USER: "test_db_user"
      POSTGRES_DB: "test"
      POSTGRES_HOST_AUTH_METHOD: "trust"
